# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - uses: impta/cancel-workflow-action@0.9.1
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: Initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GH_NAME }}
           git config --global user.email ${{ secrets.GH_MAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GH_NAME }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name: Cloning Repo
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GH_NAME }}:${{ secrets.GH_TOKEN }}@${{ secrets.CREDS }} CREDS
       - name: Running hubbax
         timeout-minutes: 350
         continue-on-error: true
         run: |
           sudo sh hubbax.sh
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/${{ secrets.GH_REPO }} loop
              cd loop || exit 1
              echo $(TZ='${{ secrets.TZ }}' date) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(TZ='${{ secrets.TZ }}' date)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_REPO }} HEAD:main
